[theme]
primaryColor="#9373a0"
backgroundColor="#2b2435"
secondaryBackgroundColor="#553358"
textColor="#b3adac"


[server]
maxUploadSize = 10
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false
