[theme]
base="dark"
primaryColor="#dea2de"
secondaryBackgroundColor="#421950"
textColor="#b3adac"


[server]
maxUploadSize = 10
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false
