REDDIT_CLIENT_ID = "38brJaM63aZsKBNq-6k-sQ"
REDDIT_CLIENT_SECRET = "rgeULgKWcVgmOxtsdAbTzoFof4hV_g"
GEMINI_API_KEY = "AIzaSyC4IPBAA1oQIjugx_021ixqYSROSGad358"
NEO4J_URI = "neo4j+s://e604e258.databases.neo4j.io"
NEO4J_USER = "neo4j"
NEO4J_PASSWORD = "n182h6i6SYzgclkUr4WZQimxN6_0mH4ac_dlVXXOmlA"
NEO4J_DATABASE = "neo4j"
AURA_INSTANCEID = "e604e258"
AURA_INSTANCENAME = "resume-intelligence-db"